### ISSUE TITLE
Can't find documentation for installation and command line options 

### ISSUE THREAD

**Issue by Costor** [webcamoid/akvirtualcamera#9] opened 2021-01-26 16:58 UTC
Hi, 
I have installed akvirtualcamera as part of webcmoid. Now I also want to use it as stand alone virtual camera for Windows.  
Is it already available as a standalone package? If yes - I just cant find the the installation documentation (the Wiki just links back, and the webcamoid wiki gives no information on akvirtualcamera specifically).

I also can't find documentation of the command line arguments and usage.
From issue #3 I can see some installation and usage, but that is potentially much to less to use it to its full potential.

Any sourcce I'm missing and where I can read into?

Thanks, Costor

**Comment by hipersayanX** [comment] 2021-01-27 04:04
>Any sourcce I'm missing and where I can read into?

The camera is not finished yet, I won't publish any documentation or release until I can confirm that everything is working more or less fine. I'm working on this right now.

>Is it already available as a standalone package?

Yes, this program is independent of Webcamoid and you can use it to write your own front end, or use it directly from the command line.

>I also can't find documentation of the command line arguments and usage.

For creating a vcam it is:

```
AkVCamManager add-device "My virtual camera"

; It will return some device ID like 'AkVCamVideoDevice0'. Then:

AkVCamManager add-format AkVCamVideoDevice0 RGB24 640 480 30
AkVCamManager update
```

And for streaming:

```
ffmpeg -i video.webm -f rawvideo -pix_fmt rgb24 -s 640x480 - | AkVCamManager stream AkVCamVideoDevice0 RGB24 640 480
```

**Comment by markednmbr1** [comment] 2021-02-16 17:50
Hi @hipersayanX - I can't find AKVCamManager in Webcamoid installation, only AkVCamAssistant - These don't seem to handle the same commands. Is AkVCamManager only part of akvirtualcamera which isn't built in to webcamoid?

**Comment by hipersayanX** [comment] 2021-02-16 19:18
@markednmbr1 Webcamoid 8.8.0 only has the old driver since it was made with the purpose of fixing a Windows bug, and I did not wanted to spend much time in that release.
The manager is in the [daily build](https://bintray.com/webcamoid/webcamoid/akvirtualcamera/daily), and the source code is in the [master branch of akvirtualcamera](https://github.com/webcamoid/akvirtualcamera).
You can test the new driver with [Webcamoid daily build](https://bintray.com/webcamoid/webcamoid/webcamoid/daily-master) only .

**Comment by hipersayanX** [comment] 2021-06-09 20:52
I've added all the [documentation](https://github.com/webcamoid/akvirtualcamera/wiki) needed for using the vcam. Closing.

**Closed by hipersayanX** 2021-06-09 20:52 UTC
Labels: Verdict: Question
